### PR TITLE
Fix logout clearing pat bug

### LINKED ISSUE #226: [repo-agent] Logging out causes user added GITHUB PAT to be removed
Currently when a user logs out, if they have entered their own GITHUB PAT information into "Settings" it is lost.  This is a bug and should be fixed

### PR DESCRIPTION
**Pull request by aaron-prindle**
Fixes #226 

This PR fixes a bug where a user's `GITHUB_PAT` was cleared or overwritten when logging out and back in. It also transitions the project to a more robust, multi-field PAT management architecture that natively handles the hierarchy between manually provided tokens and OAuth session tokens.

## The Problem
**Token Overwriting**: Previously, OAuth login tokens and manual PATs shared the same `pat` field. Every OAuth login would wipe out any user-configured PAT.
**Addition UX Issues w/ PAT**: Currently if the OAuth token has a perm issue and the "Create Draft Review", etc. fails user's might not understand that going to "Settings" and setting a GITHUB_PAT is possible.  I've updated the relevant error alerts to include a message around this.

## The Solution
- **Multi-Field Storage**: Separated tokens into `manual_pat` (for Settings) and `oauth_pat` (for GitHub login) within Kubernetes secrets.
- **Native Runtime Resolution**: Updated the Go logic in `review-sandbox` and `issue-sandbox` to natively resolve the effective token using a hierarchy: `Manual` > `OAuth` > `Legacy Fallback`.
- **Reliable RGDs**: Updated all ResourceGraphDefinitions to inject both potential token sources as environment variables, marking them as `optional: true` to ensure pods always start even if a specific token type isn't configured yet.
- **Settings UI Enhancements**:
    - Displays active token status (Manual, OAuth, or Legacy).
    - Added a "Clear Manual PAT" button to allow easy reversion to the session token.
- **Proactive Guidance**: Enhanced error messages for PR reviews, issue comments, and repo additions to suggest configuring a GitHub Classic PAT if actions fail due to organization-level restrictions.

---

### 1. Core Fix & Architecture
- **Backend**: Updated `GetGitHubToken` and `updateUserSecret` to use the new multi-field logic.
- **Controller**: Updated `NewGithubClient` and `PersistingTokenSource` to prioritize `manual_pat` and save refreshed tokens to `oauth_pat`.
- **Sandboxes**: Modified Go entrypoints for review and issue sandboxes to resolve tokens from `MANUAL_PAT`, `OAUTH_PAT`, or `GITHUB_TOKEN` environment variables.
- **Templates**: Consolidated and updated RGDs in `k8s/`, `review-sandbox/`, `issue-sandbox/`, and `dev-sandbox/`.

### 2. Frontend & UX
- **Settings.js**: Implemented token status badges and the cleanup/clear flow.
- **App.js / AddRepo.js / UpdateRepo.js**: Enhanced alert messages with troubleshooting tips for 403/permission errors.

---

## Manually Tested, see images:
Screenshot 2025-12-19 12 37 33 PM

Screenshot 2025-12-19 12 37 57 PM
Screenshot 2025-12-19 12 38 14 PM

---

### CODE REVIEW

File: repo-agent/review-ui/ui/src/Settings.js [hunk 1]
```diff
@@ -67,19 +86,33 @@ function Settings({ onBack }) {
...
-                        <span className={`status-badge ${status.github_pat_set ? 'set' : 'missing'}`}>
-                            {status.github_pat_set ? '✅ Configured' : '⚠️ Not Set'}
-                        </span>
+                        {status.manual_pat_set && (
+                            <button type="button" className="btn btn-delete btn-sm" onClick={handleClearPat} style={{marginLeft: '10px'}}>Clear Manual PAT</button>
+                        )}
                     </div>
-                    <small>Required for watching repositories and posting comments.</small>
+                    <small>
+                        Manual PAT takes precedence over OAuth login.
```
Comment (barney-s) [inline repo-agent/review-ui/ui/src/Settings.js]: Manual PAT (getting classic PAT[https://github.com/settings/tokens]). please add a link here
