### PR TITLE
re-architect: Enable secure access to sandbox

### LINKED ISSUE #219: [repo-agent] Sandbox link not working on GKE autopilot installation
When we click the sandbox link to take us to the vscode, we see this error:

Image

For now we need to add a healthcheck yaml in all the sandbox RGDs conditionally.
Something like: 

```
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: devc-gemini-for-kubernetes-development-issue-214-fix
  namespace: barney-s
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        # The specific path your application expects
        requestPath: /healthz
        # Using the same port defined in your Service and HTTPRoute
        port: 13337
  targetRef:
    group: ""
    kind: Service
    name: devc-gemini-for-kubernetes-development-issue-214-fix-lb
```

### PR DESCRIPTION
**Pull request by barney-s**
Also fixes #219 
Obsoletes #220 

We are completely rearchitecting sandbox access. Earlier we used a HTTPRoute to route to each sandbox. But the route /sandbox/... was not protected by authentication. To make the access of sanbox secure and protected we need to rearchitect it.

### Architecture Change:

* Instead of having each Sandbox RGD create its own HTTPRoute pointing directly to the sandbox service, we now route all /sandbox/... traffic to the review-api service via the main Gateway.
* `review-api` Proxy: Add a new proxy handler in review-api that authenticates the request and then transparently forwards it to the correct internal sandbox service (devc-<name>-lb.<namespace>.svc.cluster.local).
* Cleanup: Removed the direct (unprotected) HTTPRoute definitions from the RGDs (review-sandbox, dev-sandbox, and issue-sandbox).

### Detailed Changes:

1. Modified `@k8s/ui-gateway.yaml`:
  * Updated the pr-review-api rule to match /sandbox in addition to /api. This ensures the Gateway sends sandbox traffic to your API service.

2. Updated `review-api`:
  * New File `@review-ui/review-api/pkg/api/handlers_sandbox_proxy.go`: Implemented proxySandbox, a handler that parses the namespace and name from the URL, constructs the internal service DNS name, and uses httputil.ReverseProxy to forward the request. It correctly handles path rewriting (stripping the /sandbox/ns/name prefix).
  * Modified `@review-ui/review-api/pkg/api/server.go`: Registered the new protected route group:

3. Updated RGDs:
  * Removed the httproute resource definition from:
    * @review-sandbox/review-sandbox-rgd.yaml
    * @dev-sandbox/dev-sandbox-rgd.yaml
    * @issue-sandbox/issue-sandbox-rgd.yaml

### New access

Now, when a user accesses https://<gateway>/sandbox/namespace/name, the request is:
1. Received by the Gateway.
2. Routed to review-api.
3. Authenticated by your existing AuthMiddleware.
4. Proxied to the specific sandbox service within the cluster.

### CODE REVIEW

**Review by aaron-prindle — APPROVED** [review]
Nice! Left one small nit related to logging, feel free to merge as is - LGTM

File: repo-agent/review-ui/review-api/pkg/api/handlers_sandbox_proxy.go [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+			req.Header.Set("X-Forwarded-Proto", "https")
+		} else {
+			req.Header.Set("X-Forwarded-Proto", "http")
+		}
+	}
+
+	// Error handling
+	proxy.ErrorHandler = func(w http.ResponseWriter, r *http.Request, err error) {
+		// Log the error
+		fmt.Printf("Proxy error for URL %s: %v\n", r.URL.String(), err)
```
Comment (aaron-prindle) [inline repo-agent/review-ui/review-api/pkg/api/handlers_sandbox_proxy.go]: nit: might make sense to use a structured logger here (vs fmt) as is done elsewhere

**Comment by aaron-prindle** [comment]
I wonder if there a way to have a single middleware be streaming aware vs splitting across standard and sandbox groups?  I think this is fine for now but could make life easier if there was a way to do so

File: repo-agent/review-ui/review-api/pkg/api/handlers_sandbox_proxy.go (hunk 1 above)
Comment (barney-s) [reply repo-agent/review-ui/review-api/pkg/api/handlers_sandbox_proxy.go]: switched to log.
